// xxx.ets
import { Router } from '../../route/Router'
import { AppBar } from '../../views/AppBar'

@Styles function itemStyle () {
  .width(336)
  .height(621)
  .margin({ top: 48, left: 12 })
  .borderRadius(24)
  .backgroundColor('#FFFFFF')
}

@Extend(Text) function itemTextStyle () {
  .fontColor('#182431')
  .fontSize(36)
  .fontWeight(500)
  .opacity(0.4)
  .margin({ top: 82, bottom: 40 })
}

@Entry
@Component
struct StepperPage {
  @State currentIndex: number = 0
  @State firstState: ItemState = ItemState.Normal
  @State secondState: ItemState = ItemState.Normal
  @State thirdState: ItemState = ItemState.Normal

  build() {
    Column() {
      AppBar({ title: Router.getTitle() })

      Stepper({
        index: this.currentIndex
      }) {

        // 第一个步骤页
        StepperItem() {
          Column() {
            Text('Page One')
              .itemTextStyle()
            Button('change status:' + this.firstState)
              .backgroundColor('#007dFF')
              .onClick(() => {
                this.firstState = this.firstState === ItemState.Skip ? ItemState.Normal : ItemState.Skip
              })
          }.itemStyle()
        }
        .nextLabel('Next')
        .status(this.firstState)

        // 第二个步骤页
        StepperItem() {
          Column() {
            Text('Page Two')
              .itemTextStyle()
            Button('change status:' + this.secondState)
              .backgroundColor('#007dFF')
              .onClick(() => {
                this.secondState = this.secondState === ItemState.Disabled ? ItemState.Normal : ItemState.Disabled
              })
          }.itemStyle()
        }
        .nextLabel('Next')
        .prevLabel('Previous')
        .status(this.secondState)

        // 第三个步骤页
        StepperItem() {
          Column() {
            Text('Page Three')
              .itemTextStyle()
            Button('change status:' + this.thirdState)
              .backgroundColor('#007dFF')
              .onClick(() => {
                this.thirdState = this.thirdState === ItemState.Waiting ? ItemState.Normal : ItemState.Waiting
              })
          }.itemStyle()
        }
        .status(this.thirdState)

        // 第四个步骤页
        StepperItem() {
          Column() {
            Text('Page Four')
              .itemTextStyle()
          }.itemStyle()
        }
      }
      .backgroundColor('#F1F3F5')
      .onFinish(() => {
        // 此处可处理点击最后一页的Finish时的逻辑，例如路由跳转等
        console.info('onFinish')
      })
      .onSkip(() => {
        // 此处可处理点击跳过时的逻辑，例如动态修改Stepper的index值使其跳转到某一步骤页等
        console.info('onSkip')
      })
      .onChange((prevIndex: number, index: number) => {
        this.currentIndex = index
      })
    }
  }
}