/**
 * 路由表管理
 */
export class RoutePath {
  static readonly SplashPage = "pages/SplashPage"
  static readonly HomePage = "pages/HomePage"
  static readonly BlankPage = "pages/ui/BlankPage"
  static readonly ButtonPage = "pages/ui/ButtonPage"
  static readonly CalendarPickerPage = "pages/ui/CalendarPickerPage"
  static readonly CheckboxPage = "pages/ui/CheckboxPage"
  static readonly CheckboxGroupPage = "pages/ui/CheckboxGroupPage"
  static readonly DataPanelPage = "pages/ui/DataPanelPage"
  static readonly DatePickerPage = "pages/ui/DatePickerPage"
  static readonly DividerPage = "pages/ui/DividerPage"
  static readonly FormComponentPage = "pages/ui/FormComponentPage"
  static readonly GaugePage = "pages/ui/GaugePage"
  static readonly ImagePage = "pages/ui/ImagePage"
  static readonly ImageAnimatorPage = "pages/ui/ImageAnimatorPage"
  static readonly LoadingProgressPage = "pages/ui/LoadingProgressPage"
  static readonly MarqueePage = "pages/ui/MarqueePage"
  static readonly MenuPage = "pages/ui/MenuPage"
  static readonly PatternLockPage = "pages/ui/PatternLockPage"
  static readonly ProgressPage = "pages/ui/ProgressPage"
  static readonly QRCodePage = "pages/ui/QRCodePage"
  static readonly RadioPage = "pages/ui/RadioPage"
  static readonly RatingPage = "pages/ui/RatingPage"
  static readonly RichTextPage = "pages/ui/RichTextPage"
  static readonly ScrollBarPage = "pages/ui/ScrollBarPage"
  static readonly SpanPage = "pages/ui/SpanPage"

  static readonly TextPage = "pages/ui/TextPage"

  static readonly BadgePage = "pages/ui/BadgePage"
  static readonly ColumnPage = "pages/ui/ColumnPage"
  static readonly ColumnSplitPage = "pages/ui/ColumnSplitPage"
  static readonly CounterPage = "pages/ui/CounterPage"
  static readonly EffectComponentPage = "pages/ui/EffectComponentPage"
  static readonly FlexPage = "pages/ui/FlexPage"
  static readonly FormLinkPage = "pages/ui/FormLinkPage"
  static readonly WaterFlowPage = "pages/ui/WaterFlowPage"



  static readonly CategoryPage = "pages/CategoryPage"
  static readonly ContainerPage = "pages/container/ContainerPage"
  static readonly TopicDetailPage = "pages/topicDetail/TopicDetailPage"
  static readonly DetailPage = "pages/commonDetail/DetailPage"
  static readonly CategoryDetailPage = "pages/categoryDetail/CategoryDetailPage"
  static readonly TestPage = "pages/test/TestPage"
  static readonly TestHorizontalPage = "pages/test/TestHorizontalPage"
  static readonly TestHorizontalPage2 = "pages/test/TestHorizontalPage2"
  static readonly CoordinatePage = "pages/hot/CoordinatePage"
}